#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_ai = env_modules.Clone()
env_ai.add_source_files(env.modules_sources, "*.cpp")
env_ai.add_source_files(env.modules_sources, "providers/*.cpp")
